version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app